Gather eval stats
EleutherAI/elk pull request #157
Opened 2023-03-26 22:22 UTC by reaganjlee

Adds in a new function ``get_metric_across_layers`` that can be used to get a metric score of a reporter across layers automatically. 
Some questions/things to work on
1. I'm looking to make this callable from CLI with something similar to ``elk gather`` (open to thoughts on the command)
2. The function requires that there is a reporter directory to run the tests. I test it by having a reporter directory and setting ENV_DIR to that, but am unsure on how to test this with pytest on the library by itself

2023-03-31 11:43 UTC, lauritowal requested changes
Thanks for your pull request! I've added some comments

2023-03-31 11:43 UTC, lauritowal commented on elk/evaluation/gather.py
> +    if not os.path.exists(REPORTER_DIR):
Why do you need to create the reporter_dir first?

2023-03-31 11:43 UTC, lauritowal commented on elk/evaluation/gather.py
> +import matplotlib.pyplot as plt
there are missing imports

2023-03-31 11:43 UTC, lauritowal commented on elk/promptsource/templates.py
> +INCLUDED_USERS = {"Zaid", "craffel", "lauritowal", "christykoh"}
You should remove the template changes, since this is not related to visualizing the stats

2023-04-23 02:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EleutherAI/elk?pullRequest=157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/EleutherAI/elk?pullRequest=157) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: reaganjlee<br/>:x: ChristyKoh<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EleutherAI/elk?pullRequest=157) it.</sub>

2023-05-19 13:31 UTC, norabelrose commented
Not clear what this is doing; happy to look at an updated version in the future

2023-05-19 13:31 UTC, closed without merging