spar mt prompt invar
EleutherAI/elk pull request #184
Opened 2023-04-12 12:13 UTC by ChristyKoh

Fixes #172 
- add merge_templates_from method to DatasetTemplates
- generate combined templates.yaml when PromptConfig is initialized

2023-04-12 17:10 UTC, lauritowal requested changes

2023-04-12 17:10 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +                # TODO: Verify that cols are same; if not, warn that templates
we should add that

2023-04-12 20:02 UTC, ChristyKoh commented on elk/extraction/prompt_loading.py
> +    print()
Done.

2023-04-12 20:02 UTC, ChristyKoh commented on elk/extraction/prompt_loading.py
> +                # TODO: Verify that cols are same; if not, warn that templates
Done.

2023-04-12 20:03 UTC, ChristyKoh commented on elk/extraction/extraction.py
> +    # extraneous, remove ?
My bad, I realized they're used in the get_splits() function above. Added a comment.

2023-04-16 18:17 UTC, lauritowal requested changes
Thanks for the pull-request! Just tried it out and it seems to work. You might want to split up your code into multiple functions to make it a bit more readable. I've added some comments.

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        # Combining prompts
Let's maybe split this into multiple functions

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        if self.combined_template_path:
You can remove this, since you are checking above already

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        if self.combined_template_path:
but yeah, this can also be an own function

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        combined_template_path: Path to save a combined template file to, when testing
maybe combined_template_output_path describes what it is better.

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        combined_template_path: Path to save a combined template file to, when testing
when testing --> when applying or when using ?

2023-04-16 18:17 UTC, lauritowal commented on elk/extraction/prompt_loading.py
> +        if combined_template_path == "":
nitpick, but I guess 

`if not combined_template_path: `

is a little bit cleaner

2023-04-20 11:45 UTC, lauritowal approved these changes

2023-04-20 11:46 UTC, merged