Ccs platt scale
EleutherAI/elk pull request #244
Opened 2023-05-10 19:47 UTC by lauritowal

2023-05-10 19:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EleutherAI/elk?pullRequest=244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/EleutherAI/elk?pullRequest=244) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: norabelrose<br/>:x: lauritofzi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EleutherAI/elk?pullRequest=244) it.</sub>

2023-05-10 20:56 UTC, norabelrose requested changes
almost

2023-05-10 20:56 UTC, norabelrose commented on elk/training/ccs_reporter.py
> +        # return self.probe(self.norm(x)).squeeze(-1)
Just remove this comment and then LGTM

2023-05-10 23:12 UTC, AlexTMallen approved these changes

2023-05-16 13:11 UTC, lauritowal commented on elk/training/ccs_reporter.py
> +        # return self.probe(self.norm(x)).squeeze(-1)
done

2023-05-17 16:49 UTC, AlexTMallen approved these changes

2023-05-22 23:01 UTC, norabelrose approved these changes
LGTM

2023-05-22 23:03 UTC, merged